### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by HiroshiNakano0140** [HiroshiNakano0140/chat-space#9]
# IPアドレス
52.68.158.43

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

### [修正箇所]
**①グループを作成して１回目のメッセージ送信で自動更新ができるようにしましょう
②グループ編集画面にて「更新する」ボタンを押した後に、「http://52.68.158.43/ 」ではなく、「http://52.68.158.43/groups/●/messages」の飛ぶようにしましょう
（※●は任意のグループのIDです）**

①の様子の画像↓
<img width="1431" alt="自動更新" src="https://user-images.githubusercontent.com/49669977/87518584-6c841180-c6bb-11ea-990f-320e7e792e52.png">


修正が完了次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by HiroshiNakano0140** [comment]
上記２点、修正いたしました。
よろしくお願いいたします。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
※今後実装に関する質問がありましたら、メンターに確認をお願いします！
